version: '3.5'

services:
  max-cropping-tool:
    container_name: front-end-web-app
    image: vatsalpatel9876/front-end-app:v1
    ports:
      - '8080:8080'

  max-model:
    container_name: ai-image-prediction
    image: codait/max-image-segmenter
    ports:
      - '5000:5000'
    environment:
      - CORS_ENABLE=true
